spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:ventas_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:abcd}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# IMPORTANTE: Usar nombre del contenedor Docker
inventario:
  #url: ${INVENTARIO_URL:http://ms-inventario:8082}
  url: ${INVENTARIO_URL:http://localhost:8082}

logging:
  level:
    com.empresa.ventas: DEBUG  # CAMBIADO A DEBUG
    org.example.msventas: DEBUG
    org.springframework.cloud.openfeign: DEBUG  # PARA VER LLAMADAS FEIGN

