spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/ventas_db
    username: ${DB_USER:ventas}
    password: ${DB_PASSWORD:ventas123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

inventario:
  url: http://inventario-service:8082

logging:
  level:
    com.empresa.ventas: INFO
