spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/ventas_db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

inventario:
  url: http://localhost:8082

logging:
  level:
    com.empresa.ventas: DEBUG
